FROM nginx:alpine

# Copiar el index.html al directorio de Nginx
COPY index.html /usr/share/nginx/html/

# Copiar el archivo de configuración personalizado
COPY nginx.conf /etc/nginx/conf.d/default.conf
